#!/usr/bin/python
import sys

import Environment

class Project:
	def __init__( self, path ):
		env = Environment.Env()
		
		# Parse the project config file
		env.configure( path )
		env.build( path )

		# Output the makefile
		env.output.start( 'Writing makefile...' )
		env.make.write()
		env.output.success( 'done' )
	
def main():
	project = Project( './project.lupine' )

if __name__ == '__main__':
	main()
