#!/usr/bin/python
import sys
import imp
from optparse import OptionParser, OptionGroup

import Environment

VERSION = '0.0'

class Project:
	def __init__( self, path ):
		env = Environment.Env()
		
		# Parse the project config file
		try:
			project = imp.load_source( 'project', path )
		except IOError:
			self.env.output.error( 'No project definition found' )

		# Set up our command line options
		option_parser = OptionParser( version='%prog {0}'.format( VERSION ))
		project.configure( env )
		option_parser.parse_args()
		
		project.build( env, env.args )

		# Output the makefile
		env.output.start( 'Writing makefile...' )
		env.make.write()
		env.output.success( 'done' )
	
def main():
	project = Project( './project.lupine' )

if __name__ == '__main__':
	main()
